---
- name: ServiceNow Change Validation Playbook
  hosts: localhost
  gather_facts: false
  vars:
    # Target Change Record

  tasks:
    - name: Update Work Notes and Additional Comments
      servicenow.itsm.change_request:
        instance:
          host: "{{ snow_instance }}"
          username: "{{ snow_username }}"
          password: "{{ snow_password }}"
        number: "{{ change_number }}"
        state: new
        other:
          work_notes: "Ansible has Updated this record"
